// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/ui-prompts-library/AppleGlass.tsx": () => import("../components/mockups/ui-prompts-library/AppleGlass.tsx"),
  "./components/mockups/ui-prompts-library/DiscordStyle.tsx": () => import("../components/mockups/ui-prompts-library/DiscordStyle.tsx"),
  "./components/mockups/ui-prompts-library/LinearStyle.tsx": () => import("../components/mockups/ui-prompts-library/LinearStyle.tsx"),
  "./components/mockups/ui-prompts-library/NotionOpenCode.tsx": () => import("../components/mockups/ui-prompts-library/NotionOpenCode.tsx")
};
