// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/ui-prompts-library/AlohaCoastal.tsx": () => import("../components/mockups/ui-prompts-library/AlohaCoastal.tsx"),
  "./components/mockups/ui-prompts-library/AppleGlass.tsx": () => import("../components/mockups/ui-prompts-library/AppleGlass.tsx"),
  "./components/mockups/ui-prompts-library/CocktailEditorial.tsx": () => import("../components/mockups/ui-prompts-library/CocktailEditorial.tsx"),
  "./components/mockups/ui-prompts-library/DiscordStyle.tsx": () => import("../components/mockups/ui-prompts-library/DiscordStyle.tsx"),
  "./components/mockups/ui-prompts-library/LinearStyle.tsx": () => import("../components/mockups/ui-prompts-library/LinearStyle.tsx"),
  "./components/mockups/ui-prompts-library/MoonishCosmic.tsx": () => import("../components/mockups/ui-prompts-library/MoonishCosmic.tsx"),
  "./components/mockups/ui-prompts-library/NoalDrinkBar.tsx": () => import("../components/mockups/ui-prompts-library/NoalDrinkBar.tsx"),
  "./components/mockups/ui-prompts-library/NotionOpenCode.tsx": () => import("../components/mockups/ui-prompts-library/NotionOpenCode.tsx"),
  "./components/mockups/ui-prompts-library/SamuraiCanvas.tsx": () => import("../components/mockups/ui-prompts-library/SamuraiCanvas.tsx"),
  "./components/mockups/ui-prompts-library/SmartHomeDash.tsx": () => import("../components/mockups/ui-prompts-library/SmartHomeDash.tsx")
};
